-------------------------------------------------------------------------------
Test set: dao.Sql2oCategoryDaoTest
-------------------------------------------------------------------------------
Tests run: 11, Failures: 0, Errors: 11, Skipped: 0, Time elapsed: 0.207 sec <<< FAILURE! - in dao.Sql2oCategoryDaoTest
getAll(dao.Sql2oCategoryDaoTest)  Time elapsed: 0.046 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: password authentication failed for user "wangui"
	at dao.Sql2oCategoryDaoTest.setUp(Sql2oCategoryDaoTest.java:29)
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "wangui"
	at dao.Sql2oCategoryDaoTest.setUp(Sql2oCategoryDaoTest.java:29)

getAll(dao.Sql2oCategoryDaoTest)  Time elapsed: 0.047 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: password authentication failed for user "wangui"
	at dao.Sql2oCategoryDaoTest.tearDown(Sql2oCategoryDaoTest.java:34)
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "wangui"
	at dao.Sql2oCategoryDaoTest.tearDown(Sql2oCategoryDaoTest.java:34)

deleteCategoryById(dao.Sql2oCategoryDaoTest)  Time elapsed: 0.036 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: password authentication failed for user "wangui"
	at dao.Sql2oCategoryDaoTest.setUp(Sql2oCategoryDaoTest.java:29)
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "wangui"
	at dao.Sql2oCategoryDaoTest.setUp(Sql2oCategoryDaoTest.java:29)

deleteCategoryById(dao.Sql2oCategoryDaoTest)  Time elapsed: 0.039 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: password authentication failed for user "wangui"
	at dao.Sql2oCategoryDaoTest.tearDown(Sql2oCategoryDaoTest.java:34)
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "wangui"
	at dao.Sql2oCategoryDaoTest.tearDown(Sql2oCategoryDaoTest.java:34)

findById(dao.Sql2oCategoryDaoTest)  Time elapsed: 0.028 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: password authentication failed for user "wangui"
	at dao.Sql2oCategoryDaoTest.setUp(Sql2oCategoryDaoTest.java:29)
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "wangui"
	at dao.Sql2oCategoryDaoTest.setUp(Sql2oCategoryDaoTest.java:29)

findById(dao.Sql2oCategoryDaoTest)  Time elapsed: 0.029 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: password authentication failed for user "wangui"
	at dao.Sql2oCategoryDaoTest.tearDown(Sql2oCategoryDaoTest.java:34)
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "wangui"
	at dao.Sql2oCategoryDaoTest.tearDown(Sql2oCategoryDaoTest.java:34)

updateCategoryById(dao.Sql2oCategoryDaoTest)  Time elapsed: 0.037 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: password authentication failed for user "wangui"
	at dao.Sql2oCategoryDaoTest.setUp(Sql2oCategoryDaoTest.java:29)
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "wangui"
	at dao.Sql2oCategoryDaoTest.setUp(Sql2oCategoryDaoTest.java:29)

updateCategoryById(dao.Sql2oCategoryDaoTest)  Time elapsed: 0.042 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: password authentication failed for user "wangui"
	at dao.Sql2oCategoryDaoTest.tearDown(Sql2oCategoryDaoTest.java:34)
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "wangui"
	at dao.Sql2oCategoryDaoTest.tearDown(Sql2oCategoryDaoTest.java:34)

idIsSetUpCorrectly(dao.Sql2oCategoryDaoTest)  Time elapsed: 0.043 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: password authentication failed for user "wangui"
	at dao.Sql2oCategoryDaoTest.setUp(Sql2oCategoryDaoTest.java:29)
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "wangui"
	at dao.Sql2oCategoryDaoTest.setUp(Sql2oCategoryDaoTest.java:29)

idIsSetUpCorrectly(dao.Sql2oCategoryDaoTest)  Time elapsed: 0.044 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: password authentication failed for user "wangui"
	at dao.Sql2oCategoryDaoTest.tearDown(Sql2oCategoryDaoTest.java:34)
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "wangui"
	at dao.Sql2oCategoryDaoTest.tearDown(Sql2oCategoryDaoTest.java:34)

dao.Sql2oCategoryDaoTest  Time elapsed: 0.045 sec  <<< ERROR!
java.lang.NullPointerException
	at dao.Sql2oCategoryDaoTest.shutDown(Sql2oCategoryDaoTest.java:39)

