<?xml version="1.0" encoding="UTF-8"?>
<testsuite xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report.xsd" name="dao.Sql2oBusinessDaoTest" time="0.96" tests="15" errors="15" skipped="0" failures="0">
  <properties>
    <property name="java.runtime.name" value="OpenJDK Runtime Environment"/>
    <property name="java.vm.version" value="11.0.6+10"/>
    <property name="sun.boot.library.path" value="/home/stevie-yazz/.sdkman/candidates/java/11.0.6.hs-adpt/lib"/>
    <property name="maven.multiModuleProjectDirectory" value="/home/stevie-yazz/IdeaProjects/Azure-businesses"/>
    <property name="java.vm.vendor" value="AdoptOpenJDK"/>
    <property name="java.vendor.url" value="https://adoptopenjdk.net/"/>
    <property name="guice.disable.misplaced.annotation.check" value="true"/>
    <property name="path.separator" value=":"/>
    <property name="java.vm.name" value="OpenJDK 64-Bit Server VM"/>
    <property name="sun.os.patch.level" value="unknown"/>
    <property name="user.country" value="US"/>
    <property name="sun.java.launcher" value="SUN_STANDARD"/>
    <property name="java.vm.specification.name" value="Java Virtual Machine Specification"/>
    <property name="user.dir" value="/home/stevie-yazz/IdeaProjects/Azure-businesses"/>
    <property name="java.vm.compressedOopsMode" value="32-bit"/>
    <property name="java.runtime.version" value="11.0.6+10"/>
    <property name="java.awt.graphicsenv" value="sun.awt.X11GraphicsEnvironment"/>
    <property name="os.arch" value="amd64"/>
    <property name="java.io.tmpdir" value="/tmp"/>
    <property name="line.separator" value="&#10;"/>
    <property name="java.vm.specification.vendor" value="Oracle Corporation"/>
    <property name="os.name" value="Linux"/>
    <property name="classworlds.conf" value="/usr/share/maven/bin/m2.conf"/>
    <property name="sun.jnu.encoding" value="UTF-8"/>
    <property name="java.library.path" value="/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib"/>
    <property name="maven.conf" value="/usr/share/maven/conf"/>
    <property name="jdk.debug" value="release"/>
    <property name="java.class.version" value="55.0"/>
    <property name="java.specification.name" value="Java Platform API Specification"/>
    <property name="sun.management.compiler" value="HotSpot 64-Bit Tiered Compilers"/>
    <property name="os.version" value="5.3.0-52-generic"/>
    <property name="library.jansi.path" value="/usr/share/maven/lib/jansi-native"/>
    <property name="user.home" value="/home/stevie-yazz"/>
    <property name="user.timezone" value="Africa/Nairobi"/>
    <property name="java.awt.printerjob" value="sun.print.PSPrinterJob"/>
    <property name="file.encoding" value="UTF-8"/>
    <property name="java.specification.version" value="11"/>
    <property name="user.name" value="stevie-yazz"/>
    <property name="java.class.path" value="/usr/share/maven/boot/plexus-classworlds-2.x.jar"/>
    <property name="java.vm.specification.version" value="11"/>
    <property name="sun.arch.data.model" value="64"/>
    <property name="sun.java.command" value="org.codehaus.plexus.classworlds.launcher.Launcher heroku:deploy"/>
    <property name="java.home" value="/home/stevie-yazz/.sdkman/candidates/java/11.0.6.hs-adpt"/>
    <property name="user.language" value="en"/>
    <property name="java.specification.vendor" value="Oracle Corporation"/>
    <property name="awt.toolkit" value="sun.awt.X11.XToolkit"/>
    <property name="java.vm.info" value="mixed mode"/>
    <property name="java.version" value="11.0.6"/>
    <property name="securerandom.source" value="file:/dev/./urandom"/>
    <property name="java.vendor" value="AdoptOpenJDK"/>
    <property name="maven.home" value="/usr/share/maven"/>
    <property name="file.separator" value="/"/>
    <property name="java.version.date" value="2020-01-14"/>
    <property name="java.vendor.url.bug" value="https://github.com/AdoptOpenJDK/openjdk-support/issues"/>
    <property name="sun.io.unicode.encoding" value="UnicodeLittle"/>
    <property name="sun.cpu.endian" value="little"/>
    <property name="java.vendor.version" value="AdoptOpenJDK"/>
    <property name="sun.desktop" value="gnome"/>
    <property name="sun.cpu.isalist" value=""/>
  </properties>
  <testcase name="updateBusinessById" classname="dao.Sql2oBusinessDaoTest" time="0.698">
    <error message="Could not acquire a connection from DataSource - FATAL: password authentication failed for user &quot;wangui&quot;" type="org.sql2o.Sql2oException">org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: password authentication failed for user "wangui"
	at dao.Sql2oBusinessDaoTest.setUp(Sql2oBusinessDaoTest.java:31)
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "wangui"
	at dao.Sql2oBusinessDaoTest.setUp(Sql2oBusinessDaoTest.java:31)
</error>
    <system-out><![CDATA[connected to database
]]></system-out>
  </testcase>
  <testcase name="updateBusinessById" classname="dao.Sql2oBusinessDaoTest" time="0.704">
    <error message="Could not acquire a connection from DataSource - FATAL: password authentication failed for user &quot;wangui&quot;" type="org.sql2o.Sql2oException">org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: password authentication failed for user "wangui"
	at dao.Sql2oBusinessDaoTest.tearDown(Sql2oBusinessDaoTest.java:36)
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "wangui"
	at dao.Sql2oBusinessDaoTest.tearDown(Sql2oBusinessDaoTest.java:36)
</error>
  </testcase>
  <testcase name="filterByMostRecent" classname="dao.Sql2oBusinessDaoTest" time="0.039">
    <error message="Could not acquire a connection from DataSource - FATAL: password authentication failed for user &quot;wangui&quot;" type="org.sql2o.Sql2oException">org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: password authentication failed for user "wangui"
	at dao.Sql2oBusinessDaoTest.setUp(Sql2oBusinessDaoTest.java:31)
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "wangui"
	at dao.Sql2oBusinessDaoTest.setUp(Sql2oBusinessDaoTest.java:31)
</error>
    <system-out><![CDATA[connected to database
]]></system-out>
  </testcase>
  <testcase name="filterByMostRecent" classname="dao.Sql2oBusinessDaoTest" time="0.042">
    <error message="Could not acquire a connection from DataSource - FATAL: password authentication failed for user &quot;wangui&quot;" type="org.sql2o.Sql2oException">org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: password authentication failed for user "wangui"
	at dao.Sql2oBusinessDaoTest.tearDown(Sql2oBusinessDaoTest.java:36)
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "wangui"
	at dao.Sql2oBusinessDaoTest.tearDown(Sql2oBusinessDaoTest.java:36)
</error>
  </testcase>
  <testcase name="findByIdReturnsCorrectInstance" classname="dao.Sql2oBusinessDaoTest" time="0.039">
    <error message="Could not acquire a connection from DataSource - FATAL: password authentication failed for user &quot;wangui&quot;" type="org.sql2o.Sql2oException">org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: password authentication failed for user "wangui"
	at dao.Sql2oBusinessDaoTest.setUp(Sql2oBusinessDaoTest.java:31)
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "wangui"
	at dao.Sql2oBusinessDaoTest.setUp(Sql2oBusinessDaoTest.java:31)
</error>
    <system-out><![CDATA[connected to database
]]></system-out>
  </testcase>
  <testcase name="findByIdReturnsCorrectInstance" classname="dao.Sql2oBusinessDaoTest" time="0.04">
    <error message="Could not acquire a connection from DataSource - FATAL: password authentication failed for user &quot;wangui&quot;" type="org.sql2o.Sql2oException">org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: password authentication failed for user "wangui"
	at dao.Sql2oBusinessDaoTest.tearDown(Sql2oBusinessDaoTest.java:36)
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "wangui"
	at dao.Sql2oBusinessDaoTest.tearDown(Sql2oBusinessDaoTest.java:36)
</error>
  </testcase>
  <testcase name="setUpIdWorks" classname="dao.Sql2oBusinessDaoTest" time="0.045">
    <error message="Could not acquire a connection from DataSource - FATAL: password authentication failed for user &quot;wangui&quot;" type="org.sql2o.Sql2oException">org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: password authentication failed for user "wangui"
	at dao.Sql2oBusinessDaoTest.setUp(Sql2oBusinessDaoTest.java:31)
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "wangui"
	at dao.Sql2oBusinessDaoTest.setUp(Sql2oBusinessDaoTest.java:31)
</error>
    <system-out><![CDATA[connected to database
]]></system-out>
  </testcase>
  <testcase name="setUpIdWorks" classname="dao.Sql2oBusinessDaoTest" time="0.049">
    <error message="Could not acquire a connection from DataSource - FATAL: password authentication failed for user &quot;wangui&quot;" type="org.sql2o.Sql2oException">org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: password authentication failed for user "wangui"
	at dao.Sql2oBusinessDaoTest.tearDown(Sql2oBusinessDaoTest.java:36)
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "wangui"
	at dao.Sql2oBusinessDaoTest.tearDown(Sql2oBusinessDaoTest.java:36)
</error>
  </testcase>
  <testcase name="deleteById" classname="dao.Sql2oBusinessDaoTest" time="0.033">
    <error message="Could not acquire a connection from DataSource - FATAL: password authentication failed for user &quot;wangui&quot;" type="org.sql2o.Sql2oException">org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: password authentication failed for user "wangui"
	at dao.Sql2oBusinessDaoTest.setUp(Sql2oBusinessDaoTest.java:31)
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "wangui"
	at dao.Sql2oBusinessDaoTest.setUp(Sql2oBusinessDaoTest.java:31)
</error>
    <system-out><![CDATA[connected to database
]]></system-out>
  </testcase>
  <testcase name="deleteById" classname="dao.Sql2oBusinessDaoTest" time="0.035">
    <error message="Could not acquire a connection from DataSource - FATAL: password authentication failed for user &quot;wangui&quot;" type="org.sql2o.Sql2oException">org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: password authentication failed for user "wangui"
	at dao.Sql2oBusinessDaoTest.tearDown(Sql2oBusinessDaoTest.java:36)
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "wangui"
	at dao.Sql2oBusinessDaoTest.tearDown(Sql2oBusinessDaoTest.java:36)
</error>
  </testcase>
  <testcase name="allInstancesOfSelectedCategoryAreReturned" classname="dao.Sql2oBusinessDaoTest" time="0.025">
    <error message="Could not acquire a connection from DataSource - FATAL: password authentication failed for user &quot;wangui&quot;" type="org.sql2o.Sql2oException">org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: password authentication failed for user "wangui"
	at dao.Sql2oBusinessDaoTest.setUp(Sql2oBusinessDaoTest.java:31)
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "wangui"
	at dao.Sql2oBusinessDaoTest.setUp(Sql2oBusinessDaoTest.java:31)
</error>
    <system-out><![CDATA[connected to database
]]></system-out>
  </testcase>
  <testcase name="allInstancesOfSelectedCategoryAreReturned" classname="dao.Sql2oBusinessDaoTest" time="0.026">
    <error message="Could not acquire a connection from DataSource - FATAL: password authentication failed for user &quot;wangui&quot;" type="org.sql2o.Sql2oException">org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: password authentication failed for user "wangui"
	at dao.Sql2oBusinessDaoTest.tearDown(Sql2oBusinessDaoTest.java:36)
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "wangui"
	at dao.Sql2oBusinessDaoTest.tearDown(Sql2oBusinessDaoTest.java:36)
</error>
  </testcase>
  <testcase name="allInstancesAreReturned" classname="dao.Sql2oBusinessDaoTest" time="0.028">
    <error message="Could not acquire a connection from DataSource - FATAL: password authentication failed for user &quot;wangui&quot;" type="org.sql2o.Sql2oException">org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: password authentication failed for user "wangui"
	at dao.Sql2oBusinessDaoTest.setUp(Sql2oBusinessDaoTest.java:31)
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "wangui"
	at dao.Sql2oBusinessDaoTest.setUp(Sql2oBusinessDaoTest.java:31)
</error>
    <system-out><![CDATA[connected to database
]]></system-out>
  </testcase>
  <testcase name="allInstancesAreReturned" classname="dao.Sql2oBusinessDaoTest" time="0.029">
    <error message="Could not acquire a connection from DataSource - FATAL: password authentication failed for user &quot;wangui&quot;" type="org.sql2o.Sql2oException">org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: password authentication failed for user "wangui"
	at dao.Sql2oBusinessDaoTest.tearDown(Sql2oBusinessDaoTest.java:36)
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "wangui"
	at dao.Sql2oBusinessDaoTest.tearDown(Sql2oBusinessDaoTest.java:36)
</error>
  </testcase>
  <testcase name="dao.Sql2oBusinessDaoTest" classname="dao.Sql2oBusinessDaoTest" time="0.036">
    <error type="java.lang.NullPointerException">java.lang.NullPointerException
	at dao.Sql2oBusinessDaoTest.shutDown(Sql2oBusinessDaoTest.java:41)
</error>
  </testcase>
</testsuite>